config/routes.rb
Rails.application.routes.draw do

  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, only: [:show, :destroy, :update] do
     get 'newg', to: 'users#new_guide', on: :member
  end

  resources :posts do
    resources :reviews, except: [:show]
  end

  get '/dashboard', to: 'pages#dashboard'
  get '/home', to: 'pages#home'
  get '/index', to: 'pages#index'
  get '/guide', to: 'pages#travel_guide'

  get 'favourites/index'
  get 'favourites/add'
  get 'favourites/remove'

  get 'followings/create'
  get 'followings/destroy'

  mount Attachinary::Engine => "/attachinary"
end

app/models/user.rb
class User < ApplicationRecord
  devise :omniauthable, omniauth_providers: [:facebook]
  has_attachment :photo

  validates :first_name, presence: :true
  validates :last_name, presence: :true
  validates :location, presence: :true, on: :update
  validates :contact, presence: :true, on: :update

  has_many :reviews, dependent: :destroy
  has_many :posts, dependent: :destroy

  has_many :user_followers, class_name: "Follow", foreign_key: "followed_id"
  has_many :followers, through: :user_followers, source: :follower

  has_many :user_followings, class_name: "Follow", foreign_key: "follower_id"
  has_many :followings, through: :user_followings, source: :followed

  has_many :favourites, class_name: "Favourite", foreign_key: "user_id"
  has_many :favourite_posts, through: :favourites, source: :post

  # has_and_belongs_to_many :languages
  has_many :languages, dependent: :destroy
  # accepts_nested_attributes_for :tasks, reject_if: :all_blank, allow_destroy: true

  accepts_nested_attributes_for :languages, allow_destroy: true, reject_if: :all_blank

   enum gender: {
    male: 0,
    female: 1,
    other: 2
    }


  def self.find_for_facebook_oauth(auth)
    user_params = auth.slice(:provider, :uid)
    user_params.merge! auth.info.slice(:email, :first_name, :last_name)
    user_params[:facebook_picture_url] = auth.info.image
    user_params[:token] = auth.credentials.token
    user_params[:token_expiry] = Time.at(auth.credentials.expires_at)
    user_params = user_params.to_h

    user = User.find_by(provider: auth.provider, uid: auth.uid)
    user ||= User.find_by(email: auth.info.email) # User did a regular sign up in the past.
    if user
      user.update(user_params)
    else
      user = User.new(user_params)
      user.password = Devise.friendly_token[0,20]  # Fake password for validation
      user.save
    end

    return user
  end

  def invalid_guide?
    self.age.blank? && self.gender.blank? && self.languages.blank? && self.location.blank? && self.contact.blank?
  end

  def self.languages_for_select
      I18nData.languages
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    user = User.find_for_facebook_oauth(request.env['omniauth.auth'])

    if user.persisted?
      sign_in_and_redirect user, event: :authentication
      set_flash_message(:notice, :success, kind: 'Facebook') if is_navigational_format?
    else
      session['devise.facebook_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy, :new_guide]

  def index
    @users = policy_scope(User).order(created_at: :desc)
    # @users = User.all
  end

  def new_guide
    authorize @user, :new_guide?
  end

  def show
    authorize @user
  end

  def update
    authorize @user
    # current_user.languages << Language.new(language_params)
    if current_user.update(user_params)
      redirect_to current_user
    else
      render :new_guide
    end
  end

  def destroy
    authorize @user
    @user.destroy
    redirect_to root_path
  end

  private

    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:age, :gender, :travel_guide, :location, :contact, languages_attributes: [:id, :name, :_destroy])
    end
end

app/views/users/_favourites.html.erb
<div class="tab-wrapper">
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-md-offset-3 col-md-6">
        <table class="favourite-table">
          <% @user.favourite_posts.each do |favourite| %>
            <tr>
              <td width="100%">
                <%= link_to favourite.title, post_path(favourite) , class: "details" %><br>
              </td>
              <td width="90%">
                <% if current_user %>
                    <% unless current_user.favourites.where(post: favourite).exists?  %>
                      <%= link_to favourites_add_path(post_id: favourite.id),class: "empty-heart" do %>
                        <i class="fa fa-heart-o"" aria-hidden="true"></i>
                      <% end %>
                    <% else %>
                      <%= link_to favourites_remove_path(post_id: favourite.id),class: "filled-heart" do %>
                        <i class="fa fa-heart" aria-hidden="true"></i>
                      <% end %>
                    <% end %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/users/_followers.html.erb
<div class="tab-wrapper">
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-md-offset-3 col-md-6">
        <table class= "following-table">
          <% @user.followers.each do |follower| %>
            <tr>
              <td width="30%">
                <div>
                  <% unless follower.facebook_picture_url.present? %>
                    <%= cl_image_tag follower.photo.path, class: "avatar-circle-xs-small" if follower.photo.present? %>
                  <% else %>
                    <%= image_tag follower.facebook_picture_url, class:"avatar-circle-xs-small" %>
                  <% end %>
                </div>
              </td>

              <td width="30%">
                <%= link_to user_path(follower), class: "details" do %>
                 <%= follower.first_name %>&nbsp;<%=follower.last_name %>
                <% end %>
              </td>
              <% if current_user.id == @user.id %>
                <td width="30%">
                    <% unless current_user.following_ids.include?(follower.id) %>
                      <%= link_to "Follow", followings_create_path(user_id: follower.id), class:"clean-look-btn-white-follow" %>
                      <% else %>
                      <%= link_to "Unfollow", followings_destroy_path(user_id: follower.id), data: {confirm: "Are you sure you want to unfollow #{follower.first_name}?"}  , class:"clean-look-btn-white-unfollow" %>
                    <% end %>
                </td>

              <% end %>
           </tr>
          <% end %>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/users/_following.html.erb
<div class="  tab-wrapper">
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-md-offset-3 col-md-6">
        <table class="following-table">
          <% @user.followings.each do |following| %>
            <tr>
              <td width="30%">
                <div>
                  <% unless following.facebook_picture_url.present? %>
                    <%= cl_image_tag following.photo.path, class: "avatar-circle-xs-small" if following.photo.present? %>
                  <% else %>
                    <%= image_tag following.facebook_picture_url, class:"avatar-circle-xs-small" %>
                  <% end %>
                </div>
              </td>

              <td width="30%">
                <%= link_to user_path(following), class: "details" do %>
                 <%= following.first_name %>&nbsp;<%=following.last_name %>
                <% end %>
              </td>
              <% if current_user.id == @user.id %>
                <td width="30%">
                  <%# if current_user && (current_user.id != @user.id) %>
                    <% if current_user.following_ids.include?(following.id) %>
                      <%= link_to "Unfollow", followings_destroy_path(user_id: following.id), data: {confirm: "Are you sure you want to unfollow #{following.first_name}?"}  , class: "clean-look-btn-white-unfollow" %>
                    <% end %>
                  <%# end %>
                </td>
              <% end %>
            </tr>
          <% end %>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/users/_language_fields.html.erb
<div class="nested-fields">
  <%#= f.input :name, label: "Language", as: :select, collection: Language.all, label_method: :name, value_method: :name %>
  <%#= f.input :name, collection: Language.all, prompt: "Choose a language" %>
  <%# langs = Language.available(current_user) %>
  <%= f.input :name, label: "language" , collection: I18nData.languages.values, include_blank: false %>
  <%= link_to_remove_association f, class: "minus-plus" do %>
    <i class="fa fa-minus" aria-hidden="true"></i>&nbsp;&nbsp;remove language
  <% end %>

</div>

app/views/users/_travel_guide_info.html.erb
<div class="travel-guide-info-wrapper">
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-md-offset-3 col-md-6">
        <% if @user.travel_guide? %>
          <ul>
            <li>
              <h4>Location</h4>
              <h5><%= @user.location %></h5>
            </li>
            <hr>

            <li>
              <h4>Age</h4>
              <h5><%= @user.age %></h5>
            </li>
            <hr>

            <li>
              <h4>Gender</h4>
              <h5><%= @user.gender %></h5>
            </li>
            <hr>

            <li>
              <h4>Languages</h4>
              <% if @user.languages.present? %>
                <% @user.languages.each do |language| %>
                  <h5><%= language.name %></h5>
                <% end %>
              <% end %>
            </li>
            <hr>

            <li>
              <h4>Contact me</h4>
              <h5><%= @user.contact %></h5>
            </li>
          </ul>
            <% elsif @user.travel_guide.nil? %>
              <%= link_to "Become a travel guide", newg_user_path %>
            <% else %>

              <div class="off-duty">
                <h3 class="text-center">Off Duty !</h3>
              </div>
            <% end %>

        <hr>
        <% if current_user.id == @user.id && !current_user.invalid_guide? %>
          <%= simple_form_for current_user do |f| %>
            <%= f.input :travel_guide, label: "Available", class: "form-control" %>
            <%= f.submit "submit", class: "clean-look-btn-white submit-guide-info"%>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/new_guide.html.erb
<%= render 'shared/travel_guide' %>

app/views/users/show.html.erb
<% content_for(:title) do %>
  Profile | Missing Out
<% end %>

<div class="profile-wrapper">

  <!-- User avatar  -->
  <div class="profile-avatar  profile-pic">
    <% unless @user.facebook_picture_url.present? %>
      <%= cl_image_tag @user.photo.path, :transformation=>[{:width=>120, :height=>120, :gravity=>"face", :radius=>"max", :crop=>"thumb"}] if @user.photo.present? %>
    <% else %>
      <%= image_tag @user.facebook_picture_url %>
    <% end %>


  </div>

  <div class="profile-name">
    <h3><%= @user.first_name %> <%= @user.last_name %></h3>
  </div>


  <!-- edit profile link -->
  <div class="profile-edit">
    <%= link_to edit_user_registration_path do %>
      <i class="fa fa-cog" aria-hidden="true"></i>
    <% end if current_user.id == @user.id %>
  </div>
  <!-- user first name -->

  <div class="profile-guide">
      <% if current_user.id == @user.id %>
        <% if @user.invalid_guide? %>
          <%= link_to "Become a Guide", newg_user_path, class: "clean-look-btn-white guide-btn" %>
        <% else %>
          <%= link_to "Update guide info", newg_user_path, class: "clean-look-btn-white guide-btn" %>
        <% end %>
      <% end %>
  </div>


  <!-- Follow/unfollow button -->
  <div class="profile-follow">
    <% if current_user && (current_user.id != @user.id) %>
      <% unless @user.follower_ids.include?(current_user.id) %>
        <%= link_to "Follow", followings_create_path(user_id: @user.id), class: "clean-look-btn-white-follow-p" %>
      <% else %>
        <%= link_to "Unfollow", followings_destroy_path(user_id: @user.id), class: "clean-look-btn-white-unfollow-p" %>
      <% end %>
    <% end %>
  </div>
</div>


<!-- follwings/followers tabs -->
<div class="tabs-bg">
  <% if user_signed_in? %>
    <!-- Nav tabs -->
    <div class="tabs">
      <ul class="nav nav-tabs" role="tablist">
        <li role="presentation" class="active"><a href="#following" aria-controls="following" role="tab" data-toggle="tab">Following</a></li>
        <li role="presentation"><a href="#followers" aria-controls="followers" role="tab" data-toggle="tab">Followers</a></li>
        <li role="presentation"><a href="#favourites" aria-controls="favourites" role="tab" data-toggle="tab">Favorites</a></li>
        <% unless @user.invalid_guide? %>
          <li role="presentation"><a href="#travel_guide" aria-controls="travel_guide" role="tab" data-toggle="tab">Guide</a></li>
        <% end %>
      </ul>
    </div>

    <!-- Tab panes -->
    <div class="tab-content">
      <div role="tabpanel" class="tab-pane active" id="following"><%= render 'following' %></div>
      <div role="tabpanel" class="tab-pane" id="followers"><%= render 'followers' %></div>
      <div role="tabpanel" class="tab-pane" id="favourites"><%= render 'favourites' %></div>
      <%# unless @user.invalid_guide? %>
      <div role="tabpanel" class="tab-pane" id="travel_guide"><%= render 'travel_guide_info'%></div>
      <%# end %>
    </div>
  <% end %>
</div>

<% content_for(:after_js) do %>
  <script>
    var url = document.location.toString();
    if (url.match('#')) {
        $('.nav-tabs a[href="#' + url.split('#')[1] + '"]').tab('show');
    }

    // Change hash for page-reload
    $('.nav-tabs a').on('shown.bs.tab', function (e) {
        window.location.hash = e.target.hash;
    })
  </script>
<% end %>