config/routes.rb
Rails.application.routes.draw do

  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, only: [:show, :destroy, :update] do
     get 'newg', to: 'users#new_guide', on: :member
  end

  resources :posts do
    resources :reviews, except: [:show]
  end

  get '/dashboard', to: 'pages#dashboard'
  get '/home', to: 'pages#home'
  get '/index', to: 'pages#index'
  get '/guide', to: 'pages#travel_guide'

  get 'favourites/index'
  get 'favourites/add'
  get 'favourites/remove'

  get 'followings/create'
  get 'followings/destroy'

  mount Attachinary::Engine => "/attachinary"
end

app/views/shared/_filter.html.erb
<%= form_tag index_path, method: :get  do %>
  <div class="filter">
    <%= image_tag 'filter.png' %>
  </div>
  <div class="location-search-bar">
    <%= text_field_tag :search, params[:search], placeholder: "Location: eg. Meguro, Tokyo", class: "form-control" %>
  </div>
  <div class="location-search-bar-btn">
    <%= submit_tag "Search", class: "clear-padding form-control clean-look-btn-white" %>
  </div>
  <div class="clear-float"></div>
  <div id="toggleFilter" class="filter-search hidden">
    <div class="search-category-filter">
      <%= select_tag :category, options_for_select(Post.categories_for_select, params[:category]), class: "form-control" %>
    </div>
    <div class="search-category-filter">
      <%= select_tag :bounds, options_for_select({"1 km"=>1, "5 km"=>5, "10 km"=>10, "20 km"=>20, "40 km"=>40, "60 km"=>60}, params[:bounds]), class: "form-control" %>
    </div>
  </div>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div id="timerDissolve" class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div id="timerDissolve" class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-missing-out">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-missing-out-brand" do %>
    <%= image_tag "logo.png" %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-missing-out-right hidden-xs hidden-sm">

    <!-- Search form -->
    <!-- <form action="" class="navbar-missing-out-search">
      <input type="text" class="navbar-missing-out-search-input" placeholder="Search something">
      <button type="submit" class="navbar-missing-out-search-btn">
        <i class="fa fa-search"></i>
      </button>
    </form> -->

    <!-- Different navigation if login or not -->
    <% if user_signed_in? %>

      <!-- Notification -->
      <%= link_to "#", class: "navbar-missing-out-item navbar-missing-out-link" do %>
        <!-- <div class="badge-container">
          <i class="fa fa-envelope-o"></i>
          <div class="badge badge-blue">3</div>
        </div> -->
      <% end %>

      <!-- Profile picture and dropdown -->
      <div class="navbar-missing-out-item">
        <div class="dropdown">
          <% if current_user.facebook_picture_url %>
            <%= image_tag current_user.facebook_picture_url, class: " avatar-circle-small dropdown-toggle", id: "navbar-missing-out-menu", "data-toggle" => "dropdown" %>
          <% elsif current_user.photo.present? %>
            <%= cl_image_tag current_user.photo.path, :gravity=>"face", :width=>50, :height=>50, :crop=>"thumb", class: "nav-bar-avatar dropdown-toggle", id: "navbar-missing-out-menu", "data-toggle" => "dropdown"  %>
          <% else %>
            <%= image_tag "https://unsplash.it/50/50" , class: "avatar dropdown-toggle", id: "navbar-missing-out-menu", "data-toggle" => "dropdown"  %>
          <% end %>
          <ul class="dropdown-menu dropdown-menu-right navbar-missing-out-dropdown-menu">
            <li>
              <%= link_to current_user do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to dashboard_path do %>
                <i class="fa fa-globe"></i>  <%= t(".profile", default: "Dashboard") %>
              <% end %>
            </li>
            <li>
              <%= link_to favourites_index_path do %>
                <i class="fa fa-map-marker"></i>  <%= t(".profile", default: "My favorites") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>

    <% else %>

      <!-- Login text link -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-missing-out-item navbar-missing-out-link" %>

    <% end %>

    <!-- Button (call-to-action) -->
    <%#= link_to t(".top_call_to_action", default: "Post stuff"), "#", class: "navbar-missing-out-item navbar-missing-out-button btn" %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-missing-out-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-missing-out-dropdown-menu">
        <li>
          <% if user_signed_in? %>
      <!-- Notification -->
            <%= link_to user_path(current_user), class: "navbar-missing-out-item navbar-missing-out-link" do %>
              <div class="dropdown-badge-container">
                <!-- <i class="fa fa-envelope-o"></i> -->
                <!-- <div class="badge badge-blue">3</div> -->
                <div class="photo-in-mobile-menu">
                  <% if current_user.facebook_picture_url %>
                    <%= image_tag current_user.facebook_picture_url, class: "avatar-circle-xs-small dropdown-toggle", id: "navbar-missing-out-menu", "data-toggle" => "dropdown" %>
                  <% elsif current_user.photo.present? %>
                   <%= cl_image_tag current_user.photo.path, :gravity=>"face", :width=>50, :height=>50, :crop=>"thumb", class: "avatar dropdown-toggle text-center avatar-circle-xs-small", id: "navbar-missing-out-menu", "data-toggle" => "dropdown"  %>
                  <% else %>
                    <%= image_tag "https://unsplash.it/50/50" , class: "avatar dropdown-toggle text-center", id: "navbar-missing-out-menu", "data-toggle" => "dropdown"  %>
                  <% end %>
                  <p>
                    <%= current_user.first_name %>&nbsp;<%= current_user.last_name %>
                  </p>
                </div>
              </div>
            <% end %>
          <% end %>
        </li>
        <li>
          <%= link_to dashboard_path , class: "navbar-missing-out-item navbar-missing-out-link" do %>
            <i class="fa fa-globe"></i>&nbsp;Dashboard
          <% end %>
        </li>
        <li>
          <%= link_to favourites_index_path, class: "navbar-missing-out-item navbar-missing-out-link" do %>
            <i class="fa fa-map-marker"></i>  <%= t(".profile", default: "My favorites") %>
          <% end %>
        </li>
        <li>
          <% if user_signed_in? %>
            <%= link_to destroy_user_session_path, method: :delete do %>
              <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
            <% end %>
            <% else %>
              <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-missing-out-item navbar-missing-out-link" %>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_travel_guide.html.erb
<div class="update-guide-wrapper">
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-md-offset-3 col-md-6">
        <h2>Travel Guide Info</h2>
        <%= simple_form_for current_user do |f| %>
          <%= f.input :age, as: :integer, input_html: { min: '1'} %>
          <%= f.input :gender, collection: User.genders.keys %>
          <%= f.input :location %>
          <%#= current_user.languages.pluck(:name) %>
          <div id="languages">
            <%= f.simple_fields_for :languages do |language| %>
              <%= render 'language_fields', f: language %>
            <% end %>

            <div class="links">
              <%= link_to_add_association f, :languages, class: "minus-plus plus" do %>
                <hr><i class="fa fa-plus" aria-hidden="true"></i>&nbsp;&nbsp;add a language
              <% end %>
            </div>
          </div>
          <%= f.input :contact, label: "contact information" %>
          <%= f.input :travel_guide, label:"On Duty" %>
          <%#= f.input :languages, collection: I18nData.languages.values, include_blank: true  %>
          <%#= f.association :languages, as: :select %>
          <%#= f.association :languages, value_method: :name, include_blank: false %>
          <%= f.submit "Submit", class: "clean-look-btn-white back" %>
        <% end %>
      </div>
    </div>
  </div>
</div>