config/routes.rb
Rails.application.routes.draw do

  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, only: [:show, :destroy, :update] do
     get 'newg', to: 'users#new_guide', on: :member
  end

  resources :posts do
    resources :reviews, except: [:show]
  end

  get '/dashboard', to: 'pages#dashboard'
  get '/home', to: 'pages#home'
  get '/index', to: 'pages#index'
  get '/guide', to: 'pages#travel_guide'

  get 'favourites/index'
  get 'favourites/add'
  get 'favourites/remove'

  get 'followings/create'
  get 'followings/destroy'

  mount Attachinary::Engine => "/attachinary"
end

app/models/user.rb
class User < ApplicationRecord
  devise :omniauthable, omniauth_providers: [:facebook]
  has_attachment :photo

  validates :first_name, presence: :true
  validates :last_name, presence: :true
  validates :location, presence: :true, on: :update
  validates :contact, presence: :true, on: :update

  has_many :reviews, dependent: :destroy
  has_many :posts, dependent: :destroy

  has_many :user_followers, class_name: "Follow", foreign_key: "followed_id"
  has_many :followers, through: :user_followers, source: :follower

  has_many :user_followings, class_name: "Follow", foreign_key: "follower_id"
  has_many :followings, through: :user_followings, source: :followed

  has_many :favourites, class_name: "Favourite", foreign_key: "user_id"
  has_many :favourite_posts, through: :favourites, source: :post

  # has_and_belongs_to_many :languages
  has_many :languages, dependent: :destroy
  # accepts_nested_attributes_for :tasks, reject_if: :all_blank, allow_destroy: true

  accepts_nested_attributes_for :languages, allow_destroy: true, reject_if: :all_blank

   enum gender: {
    male: 0,
    female: 1,
    other: 2
    }


  def self.find_for_facebook_oauth(auth)
    user_params = auth.slice(:provider, :uid)
    user_params.merge! auth.info.slice(:email, :first_name, :last_name)
    user_params[:facebook_picture_url] = auth.info.image
    user_params[:token] = auth.credentials.token
    user_params[:token_expiry] = Time.at(auth.credentials.expires_at)
    user_params = user_params.to_h

    user = User.find_by(provider: auth.provider, uid: auth.uid)
    user ||= User.find_by(email: auth.info.email) # User did a regular sign up in the past.
    if user
      user.update(user_params)
    else
      user = User.new(user_params)
      user.password = Devise.friendly_token[0,20]  # Fake password for validation
      user.save
    end

    return user
  end

  def invalid_guide?
    self.age.blank? && self.gender.blank? && self.languages.blank? && self.location.blank? && self.contact.blank?
  end

  def self.languages_for_select
      I18nData.languages
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/views/pages/_posts_for_index.html.erb
<% posts.each do |post| %>
  <%= link_to post_path(post) do %>
    <div class="list-item">
      <div class="list-img">
        <% if post.photos.present? %>
          <%= cl_image_tag post.photos.first.path, :transformation=>[
            {:width=>400, :height=>400, :gravity=>"face", :radius=>"max", :crop=>"thumb"}], class: "post-avatar" %>
        <% else %>
          <%= image_tag "non-ava", class: "post-avatar" %>
        <% end %>
      </div>
      <div class="list-des">
        <h4><%= post.title %></h4>
          <p>Category &nbsp;:&nbsp;<%= post.category.capitalize %></p>
          <br>
      </div>
      <div class="list-link">
          <i class="fa fa-arrow-right"></i>
      </div>
    </div>
    <div class="post-review-stat">
      <% unless post.reviews.count.zero? %>
        <%= pluralize(post.reviews.count, 'review') %>
      <% else %>
        Be the first to review!
      <% end %>

      <% if post.reviews.where(recommended: true).count > 0 %>
        | <%= pluralize(post.reviews.where(recommended: true).count, 'person') %> recommended
      <% else %>
        | 0 recommended
      <% end %>

      <% if user_signed_in? %>
        | <%= pluralize( post.reviews.where(user_id: current_user.following_ids).count , 'friend') %> reviewed.
      <% end %>

    </div>
  <% end %>
  <hr>
<% end %>

app/views/pages/_posts_for_index_desktop.html.erb
<% posts.each_with_index do |post, value| %>
  <%= link_to post_path(post) do %>
    <div class="col-md-4 card-show" id="card-holder-<%= value + 1  %>">
      <div class="place-card">
        <div class="card-image">
          <% if post.photos.present? %>
          <%= cl_image_tag post.photos.first.path, :transformation=>[
            {:width=>400, :height=>300, :crop=>"thumb"}], class: "post-avatar" %>
          <% else %>
            <%= image_tag "non-ava", class: "post-avatar" %>
          <% end %>
          <div class="card-info" data-id="<%= value + 1  %>">
            <div class="card-title">
              <h4><%= post.title %></h4>
              <p>Category &nbsp;:&nbsp;<%= post.category %></p>
            </div>
            <div class="card-rec">
              <% unless post.reviews.count.zero? %>
                <p>has <%= pluralize(post.reviews.count, 'review') %>.</p>
              <% end %>

              <% if post.reviews.where(recommended: true).count > 0 %>
                <p><%= pluralize(post.reviews.where(recommended: true).count, 'person') %> recommended this.</p>
              <% end %>

              <% if post.reviews.count.zero? %>
                <p>Be the first one to review this !</p>
              <% end %>

              <% if user_signed_in? %>
                <% if post.reviews.where(user_id: current_user.following_ids).count > 0 %>
                  <p><%= pluralize( post.reviews.where(user_id: current_user.following_ids).count , 'friend') %> have reviewed this.</p>
                <% else %>
                  <p>None of your friends have reviewed this.</p>
                <% end %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
<% end %>

app/views/pages/_search.html.erb
<div class="container">
  <div class="row">
      <%= form_tag guide_path, method: :get do %>

        <div class="col-xs-12">
          <%= text_field_tag :place, params[:place], placeholder: "Location", class: "form-control"%>
        </div>
        <div class="col-xs-12 buffer"></div>
        <div class="col-xs-8">
          <%= select_tag :language, options_for_select(User.languages_for_select.values.map{|l| truncate(l, length: 12)}, params[:language]), prompt: "Language", class: "form-control" %>
        </div>

        <div class="col-xs-4">
          <%= submit_tag "Search", class: "form-control clean-look-btn"%>
        </div>
      <% end %>
  </div>
</div>

app/views/pages/dashboard.html.erb
<% content_for(:title) do %>
  Dashboard | Missing Out
<% end %>

<div class="dashboard-container-mobile hidden-sm hidden-md hidden-lg hidden-xl">
  <div class="container">
    <div class="row">
      <div class="col-xs-12">
        <div class="dashboard-header-mobile">
          <h2>Dashboard</h2>
        </div>
      </div>
      <!-- GPS LOCATION -->
      <div class="col-xs-12">
        <div class="dashboard-btn-mobile-gps">
          <div class="text-center">
            <%= link_to index_path do %>
              <%= image_tag "gps-dash.png" %>
              <p>Find Things Near You</p>
            <% end %>
          </div>
        </div>
      </div>
      <!-- ADD A GEM -->
      <div class="col-xs-6">
        <div class="dashboard-btn-mobile">
          <div class="text-center">
            <%= link_to new_post_path do %>
              <%= image_tag "hiddengem-icon.png" %>
              <p>Add a Place</p>
            <% end %>
          </div>
        </div>
      </div>
      <!-- SAVED LOCATIONS BUTTON -->
      <div class="col-xs-6">
        <div class="dashboard-btn-mobile">
          <div class="text-center">
            <%= link_to favourites_index_path do %>
              <%= image_tag "fav.png" %>
              <p>Favorites</p>
            <% end %>
          </div>
        </div>
      </div>

      <!-- TOUR GUIDE BUTTON -->
      <div class="col-xs-6">
        <div class="dashboard-btn-mobile">
          <div class="text-center">
            <%= link_to guide_path do %>
              <%= image_tag "travel-guide.png" %>
              <p>Find a Guide</p>
            <% end %>
          </div>
        </div>
      </div>
      <!-- PROFILE BUTTON -->
      <div class="col-xs-6">
        <div class="dashboard-btn-mobile">
          <div class="text-center">
            <%= link_to user_path(current_user) do %>
              <%= image_tag "myprofile-icon.png" %>
              <p>My Profile</p>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>


<div class="dashboard-container-desktop hidden-xs">
  <div class="container">
    <div class="row">
      <div class="col-xs-12">
        <div class="dashboard-header-desktop">
          <h2>Dashboard</h2>
        </div>
      </div>
      <!-- GPS LOCATION -->
      <div class="col-xs-12">
        <div class="dashboard-btn-mobile-gps">
          <div class="text-center">
            <%= link_to index_path do %>
              <%= image_tag "gps-dash.png" %>
              <p>Find Things Near You</p>
            <% end %>
          </div>
        </div>
      </div>
      <!-- ADD A GEM -->
      <div class="col-xs-3">
        <div class="dashboard-btn-mobile">
          <div class="text-center">
            <%= link_to new_post_path do %>
              <%= image_tag "hiddengem-icon.png" %>
              <p>Add a Place</p>
            <% end %>
          </div>
        </div>
      </div>
      <!-- SAVED LOCATIONS BUTTON -->
      <div class="col-xs-3">
        <div class="dashboard-btn-mobile">
          <div class="text-center">
            <%= link_to favourites_index_path do %>
              <%= image_tag "fav.png" %>
              <p>Favorites</p>
            <% end %>
          </div>
        </div>
      </div>

      <!-- TOUR GUIDE BUTTON -->
      <div class="col-xs-3">
        <div class="dashboard-btn-mobile">
          <div class="text-center">
            <%= link_to guide_path do %>
              <%= image_tag "travel-guide.png" %>
              <p>Find a Guide</p>
            <% end %>
          </div>
        </div>
      </div>
      <!-- PROFILE BUTTON -->
      <div class="col-xs-3">
        <div class="dashboard-btn-mobile">
          <div class="text-center">
            <%= link_to user_path(current_user) do %>
              <%= image_tag "myprofile-icon.png" %>
              <p>My Profile</p>
            <% end %>
          </div>
        </div>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<% content_for(:title) do %>
  Home | Missing Out
<% end %>

<div class="home-container">
  <div class="container">
    <div class="row">
      <div class="missing-out">
        <h1 class="blue-letters">Missing</h1>
        <h1 class="white-letters">Out</h1>
      </div>

      <!--                        MOBILE                          -->
      <div class="col-xs-12 hidden-sm hidden-md hidden-lg hidden-xl">
        <div class="backpacker-content text-center">
          <div class="xs-gps-icon gps-icon center-icons ">
            <%= link_to index_path do %>
              <%= image_tag "gps.png", class: 'img-gps' %>
              <p>Search by Current Location</p>
            <% end %>
          </div>
        </div>
        <div class="text-center home-sign-in">
          <% unless current_user %>

            <%= link_to user_facebook_omniauth_authorize_path ,id: "home-fb-link" do %>
              <div class="facebook">
                <i class="fa fa-facebook"></i>&nbsp; Sign in with Facebook
              </div>
            <% end %>

            <div id="sign-in-out">
              <%= link_to "Sign in", new_user_session_path %>
              <%= "|" %>
              <%= link_to "Sign up", new_user_registration_path %>
            </div>

          <% end %>
        </div>
      </div>

      <!--                           DESKTOP                              -->
      <div class="icons col-md-offset-1 col-sm-offset-1 col-sm-10 col-md-10">
        <div class="col-md-4 col-sm-4 hidden-xs center-icons">
          <div class="location-icon text-center">
            <%= link_to index_path ,class: "home-desk" do %>
              <%= image_tag "search-by-location.png" %>
              <p>Search by Address Location</p>
            <% end %>
          </div>
        </div>
        <div class="col-md-4 col-sm-4 hidden-xs">
          <div class="gps-icon center-icons text-center">
            <%= link_to index_path ,class: "home-desk" do %>
              <%= image_tag "gps.png" %>
              <p>Search by Current Location</p>
            <% end %>
          </div>
        </div>
        <div class="col-md-4 col-sm-4 hidden-xs">
          <div id="signs-in" class="sign-in-icon text-center center-icons">
            <%= link_to new_user_session_path,class: "home-desk" do %>
              <%= image_tag "sign-in.png" %>
            <% end %>
            <div id="sisgn-in" class="in-up">
              <%= link_to "Sign in", new_user_session_path ,class: "home-desk" ,class: "home-desk"%>
              <%= link_to "|" , '#' ,class: "pipe-desk"%>
              <%= link_to "Sign up", new_user_registration_path ,class: "home-desk" %>
            </div>
           </div>
        </div>
      </div>
    </div>
  </div>
</div>
<div id="sign-in-form" class="sign-in-form-container">
  <div class="sign-in-form">

  </div>
</div>

app/views/pages/index.html.erb
<% content_for(:title) do %>
  Main | Missing Out
<% end %>


<div id="map" class="" ></div>

<% content_for(:after_js) do %>
  <%= javascript_tag do %>
    function initMap() {

        function getLocation() {
            if (navigator.geolocation) {
              navigator.geolocation.getCurrentPosition(showPosition, showError);
            }
        }

        function showPosition(position) {
           $.get({
              url: "/index",
              data: {
                "lat": position["coords"]["latitude"],
                "lng": position["coords"]["longitude"],
                "search_j": <%= raw params[:search].to_json %>,
                "category": "<%= raw params[:category] %>",
                "bounds": "<%= raw params[:bounds] %>"
              },
              success:function(data) {
              }
            });
        }

        function showError( error ) {
          console.log( 'getCurrentPosition returned error', error);

          $.get({
              url: "/index",
              data: {
                "not_allowed": "user didn't allow"
              },
              success:function(data) {
              }
            });
        }
        getLocation();
    }
  <% end %>
  <script async defer
    src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GOOGLE_API_BROWSER_KEY'] %>&callback=initMap">
  </script>
<% end %>
<div class="search-container">
  <div class="container">
    <div class="row">
      <div class="col-xs-12">
        <div class="filter-category">
          <%= render 'shared/filter' %>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="container">
  <div class="row">

    <div class="col-xs-12 col-sm-12 hidden-md hidden-lg hidden-xl">
      <div class="posts_for_index">
        <%= render "posts_for_index", posts: [] %>
      </div>
    </div>

    <div class="hidden-sm hidden-xs col-md-12">
      <div class="posts_for_index_desktop">
        <%= render "posts_for_index_desktop", posts: [] %>
      </div>
    </div>

  </div>
</div>

app/views/pages/index.js.erb
var handler = Gmaps.build('Google');
handler.buildMap({ internal: { id: 'map' } }, function() {

    <% if @lat.nil? %>
      showMarkers("test", "test");
    <% else %>
      showMarkers(<%= raw @lat %>, <%= raw @lng %>);
    <% end %>

    function showMarkers(lat,lng) {
      if (lat == "test") {
        markers = handler.addMarkers(<%= raw @hash.to_json %>);
      } else {
        markers = handler.addMarkers([{
          "infowindow": "Your Location",
          "lat": lat,
          "lng": lng,
          "picture": ({
            "url": "<%= image_path "blue.png" %>",
            "width":  32,
            "height": 32
          })
        }]);
      }

    handler.bounds.extendWith(markers);

    handler.fitMapToBounds();
    if (markers.length == 0) {
      handler.getMap().setZoom(2);
    } else if (markers.length == 1) {
      handler.getMap().setZoom(15);
    }

    }

    <% unless @lat.nil? %>
      markers = handler.addMarkers(<%= raw @hash.to_json %>);
    <% end %>

});

$('.posts_for_index').html("<%= j render 'posts_for_index', posts: @posts %>");
$('.posts_for_index_desktop').html("<%= j render 'posts_for_index_desktop', posts: @posts %>");

app/views/pages/sign_in.html.erb
<% content_for(:title) do %>
  Sign in | Missing Out
<% end %>

<div class="home-container">
  <div class="container">
    <div class="row">
      <div class="col-xs-12">
        <div class="missing-out">
          <h1 class="blue-letters">Missing</h1>
          <h1 class="white-letters">Out</h1>
        </div>
        <div class="col-xs-offset-2 col-xs-8 col-md-offset-4 col-md-4">
        <form action="/action_page.php">
          <label for="email">Email</label>
          <input type="text" id="eail" name="email" placeholder="Email">

          <label for="lname">Last Name</label>
          <input type="text" id="lname" name="lastname" placeholder="Your last name..">

          <label for="country">Country</label>
          <select id="country" name="country">
            <option value="australia">Australia</option>
            <option value="canada">Canada</option>
            <option value="usa">USA</option>
          </select>

          <input type="submit" value="Submit">
        </form>
</div>

</body>
</html>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/travel_guide.html.erb
<div class="guide-wrapper">
  <h2>Find a tour guide</h2>
  <%= render 'search' %>
  <hr>
  <div class="container">
    <div class="row">
      <% @users.each do |guide| %>
        <div class="col-xs-12 col-sm-4">
            <div class="card travel-guide-card">
              <div class="card-description"><h3><%= "#{guide.first_name} #{guide.last_name}" %></h3></div>
              <div class="card-category">
                <h4><%= guide.location %></h4>
                <p>
                <% guide.languages.pluck(:name).each do |language| %>
                  <%= language %>
                <% end %>
                </p>
              </div>
                <% unless guide.facebook_picture_url.present? %>
                  <%= (cl_image_tag guide.photo.path,  :transformation=>[
            {:width=>400, :height=>400, :gravity=>"face", :crop=>"thumb"}], class:"avatar card-user") if guide.photo.present? %>
                <% else %>
                  <%= image_tag guide.facebook_picture_url, class:"avatar card-user" %>
                <% end %>
              <a class="card-link" href="<%= user_path(guide) %>#travel_guide" ></a>
            </div>
        </div>
     <% end %>
    </div>
  </div>
</div>