config/routes.rb
Rails.application.routes.draw do

  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, only: [:show, :destroy, :update] do
     get 'newg', to: 'users#new_guide', on: :member
  end

  resources :posts do
    resources :reviews, except: [:show]
  end

  get '/dashboard', to: 'pages#dashboard'
  get '/home', to: 'pages#home'
  get '/index', to: 'pages#index'
  get '/guide', to: 'pages#travel_guide'

  get 'favourites/index'
  get 'favourites/add'
  get 'favourites/remove'

  get 'followings/create'
  get 'followings/destroy'

  mount Attachinary::Engine => "/attachinary"
end

app/models/post.rb
class Post < ApplicationRecord
  has_attachments :photos, maximum: 5

  belongs_to :user
  belongs_to :location, dependent: :destroy
  has_many :reviews, dependent: :destroy


  validates :photos, presence: true
  validates :title, presence: true
  validates :description, presence: true, length: {minimum: 40}
  validates :category, presence: true

  enum category: {
    activities: 0,
    foods: 1,
    entertainment: 2
  }

  def self.search(search)
    if search
      joins(:location).where("locations.address LIKE ?", "%#{search}%")
    else
      all
    end
  end

  def self.categories_for_select
    {
      "All": "all",
      "Activities": "activities",
      "Foods": "foods",
      "Entertainment": "entertainment"
    }
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:show]
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  def index         # GET /posts
    # @posts = Post.all
    @posts = policy_scope(Post).search(params[:search]).order(created_at: :desc)
  end

  def show          # GET /posts/:id
    @review = Review.new
    authorize @post
  end

  def new           # GET /posts/new
    @post = Post.new
    @post.location = Location.new
    authorize @post
  end

  def create        # POST /posts
    @post = Post.new(post_params)
    @post.user = current_user
    @post.location = Location.new(location_params)
    authorize @post
    if @post.save
      redirect_to @post
    else
      render :new
    end
  end

  def edit          # GET /posts/:id/edit
    authorize @post
  end

  def update        # PATCH /posts/:id
    authorize @post
    @post.update(post_params)
    @post.location.update(location_params) if @post.location.present?
    redirect_to @post
  end

  def destroy       # DELETE /posts/:id
    authorize @post
    @post.destroy
    redirect_to posts_path
  end

  private

  def post_params
    params.require(:post).permit(:title, :description, :category, photos: [])
  end


  def location_params
    params.require(:post).require(:location).permit(:name, :address)
  end

  def set_post
    @post = Post.find(params[:id])
  end
end

app/views/posts/_form.html.erb
<%= simple_form_for @post do |f| %>
<div class=" col-xs-12 col-sm-offset-2 col-sm-8 col-md-offset-3 col-md-6">
  <div class="form-inputs-sign-in">
    <h4>Add a Gem</h4>
    <%= f.input :title, label: "Name of Place", placeholder: "e.g. Lou's Pizza", label: false %>
    <%= f.input :description, placeholder: "Description.. Tell me what  makes it so special", label: false %>
    <div class="help-tip">
      <p>40 Characters Minimum.</p>
    </div>
    <%= f.simple_fields_for @post.location do |l| %>
      <%= l.input :address, placeholder: "123 456, Meguro, Tokyo", label: "Address" , input_html: {class: "big-input"}, label: false %>
    <% end %>
    <%= f.input :category, collection: Post.categories.keys, label: false, prompt: "Category" %>
    <h4>Add Photos Of Your Gem</h4>
    <%= f.input :photos, as: :attachinary, label: false %>
  </div>
  <div class="form-actions text-center">
    <%= f.submit "Submit", class: 'btn btn-primary btn-width' %>
  </div>
</div>
<% end %>

app/views/posts/_review-desktop.html.erb
<div data-review-id="<%= review.id %>">
  <table class="review-table-desktop">
    <tr>
      <td width="20%">
        <%= link_to user_path(review.user) do %>
          <div class="review-avatar">
            <% unless review.user.facebook_picture_url.present? %>
              <%= cl_image_tag review.user.photo.path if review.user.photo.present? %>
            <% else %>
              <%= image_tag review.user.facebook_picture_url %>
            <% end %>
          </div>
        <% end %>
      </td>
      <td width="60%">
        <%= review.description %>
      </td>
      <td width="15%">
        <div class="recommended-img">
          <% if review.recommended %>
            <%= image_tag "recommended.png" %>
          <% end %>
        </div>
      </td>
      <td width="5%">
          <%= link_to edit_post_review_path(review.post, review) do %>
            <i class="fa fa-pencil" aria-hidden="true"></i>
          <% end if policy(review).edit? %>
          <%= link_to post_review_path(review.post, review), method: :delete,remote: true, data: {confirm: "Are you sure?"} do %>
            <i class="fa fa-trash" aria-hidden="true"></i>
          <% end if policy(review).destroy?%>
      </td>
      <tr>
        <%= review.created_at.strftime('%e/%b/%Y') %>
      </tr>
    </tr>
  </table>
  <hr>
</div>

app/views/posts/_review.html.erb
  <div data-review-id="<%= review.id %>">
  <table class="review-table">
    <tr>
      <td width="20%">
        <%= link_to user_path(review.user) do %>
          <div class="review-avatar">
            <% unless review.user.facebook_picture_url.present? %>
              <%= cl_image_tag review.user.photo.path, :gravity=>"face", :width=>150, :height=>150, :crop=>"thumb" if review.user.photo.present? %>
            <% else %>
              <%= image_tag review.user.facebook_picture_url %>
            <% end %>
          </div>
        <% end %>
      </td>
      <td width="60%">
        <%= review.description %>
      </td>
      <td min-width="15%">
        <div class="recommended-img">
          <% if review.recommended %>
            <%= image_tag "recommended.png" %>
          <% else %>
            <%= image_tag "not-recommended.png" %>
          <% end %>
        </div>
      </td>

    </tr>
  </table>
  <div class="time-review-container">
    <div class="edit-btns">
      <%= link_to edit_post_review_path(review.post, review), class: "pen-update" do %>
        <i class="fa fa-pencil" aria-hidden="true"></i>
      <% end if policy(review).edit? %>
      <%= link_to post_review_path(review.post, review), method: :delete,remote: true, data: {confirm: "Are you sure?"}, class: "trash-delete" do %>
        <i class="fa fa-trash" aria-hidden="true"></i>
      <% end if policy(review).destroy?%>
    </div>
    <div class="clear-float"></div>
    <div class="time-review">
      <%= review.created_at.strftime('%e/%b/%Y  %l:%M %p') %>
    </div>
    <div class="clear-float"></div>
  </div>
  <hr>
</div>

app/views/posts/edit.html.erb
<% content_for(:title) do %>
  Edit Post | Missing Out
<% end %>

<div class="location">
  <%= render "form" %>
</div>

app/views/posts/index.html.erb
<% content_for(:title) do %>
  Posts | Missing Out
<% end %>

<% if policy(Post).create? %>
  <%= link_to "create post", new_post_path %>
<% end %><br>

<% @posts.each do |post| %>
  <%= link_to post.title, post_path(post) %><br>
  <%= post.description %><br>
  <%= link_to "Update", edit_post_path(post) if policy(post).edit? %><br>
  <%= link_to "Delete", post_path(post), method: :delete, data: {confirm: "Are you sure?"} if policy(post).destroy? %>
<% end %>

app/views/posts/new.html.erb
<% content_for(:title) do %>
  New Post | Missing Out
<% end %>

<div class="location">
  <%= render "form" %>
</div>

app/views/posts/show.html.erb
<% content_for(:title) do %>
  <%= @post.title %> | Missing Out
<% end %>
<% content_for(:after_js) do %>
  <script type="text/javascript">
  $( document ).ready(function() {
      /* Basic Gallery */
      $( '.swipebox' ).swipebox();
      });
  </script>
<% end %>
<div class="show-container">
    <div class="banner">
      <div class="slider">
        <ul id="box-container">
          <% @post.photos.each do |photo| %>
            <li class="box">
              <a href="<%= cl_image_path(photo.path) %>" class="swipebox">
                <%= cl_image_tag(photo.path, :transformation=>[
            {:gravity=>"face", :crop=>"thumb"}])%>
              </a>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
    <div class="container">
    <div class="row">
      <div class="col-xs-12 hidden-md hidden-lg hidden-xl">
        <div class="show-box">
          <div class="show-title">
            <h2><%= @post.title %></h2>

            <p><%= @post.location.address %></p>
            <div class="icons-show">
              <%= link_to edit_post_path(@post), class: "pen-update" do %>
                <i class="fa fa-pencil" aria-hidden="true"></i>
              <% end if policy(@post).update? %>
              <%= link_to post_path(@post), method: :delete, data: {confirm: "Are you sure ?"}, class: "trash-delete"  do %>
                <i class="fa fa-trash" aria-hidden="true"></i>
              <% end if policy(@post).destroy? %>
            </div>
          </div>

          <div class="get-direction">
            <% if current_user %>
              <div class="heart-fav">
                <% unless current_user.favourites.where(post: @post).exists?  %>
                  <%= link_to favourites_add_path(post_id: @post.id), class: "empty-heart" do %>
                    <i class="fa fa-heart-o" aria-hidden="true"></i>
                  <% end %>
                <% else %>
                  <%= link_to favourites_remove_path(post_id: @post.id), class: "filled-heart" do %>
                    <i class="fa fa-heart" aria-hidden="true"></i>
                  <% end %>
                <% end %>
              </div>
            <% else %>
              <div class="heart-fav">
                <%= link_to new_user_session_path, class: "empty-heart" do %>
                  <i class="fa fa-heart-o" aria-hidden="true"></i>
                <% end %>
              </div>
            <% end %>
            <div class="direction-btn">
              <a href="https://www.google.com/maps/place/<%= @post.location.address %>" class="clean-look-btn">Directions</a>
            </div>
          </div>
        </div>
        <div class="clear"></div>
        <div class="place-review">
          <p class="word-break"><%= @post.description %></p>
        </div>
      </div>
    </div>
  </div>


  <div class="desktop-show  hidden-sm hidden-xs">
    <div class="desktop-show-info">
      <div class="desktop-show-title">
        <h2><%= @post.title %></h2>
        <p><%= @post.location.address %></p>
      </div>
      <div class="desktop-links">
        <%= link_to edit_post_path(@post), class: "pen-update" do %>
          <i class="fa fa-pencil" aria-hidden="true"></i>
        <% end if policy(@post).update? %>
      </div>
      <div class="desktop-links">
        <%= link_to post_path(@post), method: :delete, data: {confirm: "Are you sure ?"}, class: "trash-delete" do %>
          <i class="fa fa-trash" aria-hidden="true"></i>
        <% end if policy(@post).destroy? %>
      </div>
      <div class="desktop-links">
        <% if current_user %>
        <div>
          <% unless current_user.favourites.where(post: @post).exists?  %>
            <%= link_to favourites_add_path(post_id: @post.id), class: "empty-heart" do %>
              <i class="fa fa-heart-o" aria-hidden="true"></i>
            <% end %>
          <% else %>
            <%= link_to favourites_remove_path(post_id: @post.id), class: "filled-heart" do %>
              <i class="fa fa-heart" aria-hidden="true"></i>
            <% end %>
          <% end %>
        </div>
      <% else %>
        <div>
          <%= link_to new_user_session_path, class: "empty-heart" do %>
            <i class="fa fa-heart-o" aria-hidden="true"></i>
          <% end %>
        </div>
      <% end %>
      </div>
      <div class="clear-float"></div>
      <div class="desktop-show-description">
        <%= @post.description %>
      </div>
    </div>

    <div class="desktop-show-map">
      <div id="map"></div>
      <br>
      <div class="desktop-get-direction">
        <a href="https://www.google.com/maps/place/<%= @post.location.address %>" class="clean-look-btn">Directions</a>
      </div>
      <!-- Include Google Maps JS library. You should use your *own* key -->
      <script src="https://maps.google.com/maps/api/js?key=<%= ENV['GOOGLE_API_BROWSER_KEY'] %>"></script>
      <%= content_for(:after_js) do %>
          <script type="text/javascript">
            $(document).on('ready', function() {
              var handler = Gmaps.build('Google', { markers: { clusterer: undefined }});
              handler.buildMap({ internal: { id: 'map' } }, function(){
                markers = handler.addMarkers([
                  {
                    "lat": <%= @post.location.latitude %>,
                    "lng": <%= @post.location.longitude %>,
                    "infowindow": "<h1><small><%= @post.title %></small></h1>"
                  }
                ]);
                handler.bounds.extendWith(markers);
                handler.fitMapToBounds();
                handler.getMap().setZoom(16);
              });
            })
          </script>
      <% end %>

    </div>
    <div class="clear-float"></div>
  </div>
  <div class="desktop-show-review">
      <div class="review-headerq">
      <div class="">
        <div class="review-header">
          <div class="review-title">
            <h3>Reviews:</h3>
          </div>
          <% if user_signed_in? %>
            <div id="addReview" class="clean-look-btn">Add a review</div>
          <% else %>
            <%= link_to "Add a review", new_user_session_path, class: "clean-look-btn" %>
          <% end %>
        </div>
        <div id="reviewForm">
          <%= render 'reviews/form', post: @post, review: @review %>
        </div>
        <ul id="myReviews" class="my-reviews">
          <li>
            <div id="reviews">
              <% @post.reviews.reverse.each do |review| %>
                <%= render 'review' , review: review %>
              <% end %>
            </div>
          </li>
          <% if @post.reviews.count > 1 %>
            <div id="loadMore" class="text-center clean-look-btn">Load More</div>
          <% end %>
        </ul>

    <div class="desktop-show-location"></div>
  </div>
</div>